# Generated by Django 4.1.3 on 2022-11-17 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='perDy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BooleanField(verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='to',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
