# Generated by Django 4.1.7 on 2023-03-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_perdy_booking_comment_slot_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='machineTime',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='to',
            new_name='start',
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macName', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=80)),
                ('comments', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('slots', models.ManyToManyField(to='slot.slot')),
            ],
        ),
    ]
